# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/patrick/Documents/System-manageFood

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/patrick/Documents/System-manageFood

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/patrick/Documents/System-manageFood/CMakeFiles /Users/patrick/Documents/System-manageFood//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/patrick/Documents/System-manageFood/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named InventarisMBG

# Build rule for target.
InventarisMBG: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 InventarisMBG
.PHONY : InventarisMBG

# fast build rule for target.
InventarisMBG/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG.dir/build.make CMakeFiles/InventarisMBG.dir/build
.PHONY : InventarisMBG/fast

#=============================================================================
# Target rules for targets named test_algo

# Build rule for target.
test_algo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_algo
.PHONY : test_algo

# fast build rule for target.
test_algo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_algo.dir/build.make CMakeFiles/test_algo.dir/build
.PHONY : test_algo/fast

#=============================================================================
# Target rules for targets named InventarisMBG_autogen_timestamp_deps

# Build rule for target.
InventarisMBG_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 InventarisMBG_autogen_timestamp_deps
.PHONY : InventarisMBG_autogen_timestamp_deps

# fast build rule for target.
InventarisMBG_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG_autogen_timestamp_deps.dir/build.make CMakeFiles/InventarisMBG_autogen_timestamp_deps.dir/build
.PHONY : InventarisMBG_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named InventarisMBG_autogen

# Build rule for target.
InventarisMBG_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 InventarisMBG_autogen
.PHONY : InventarisMBG_autogen

# fast build rule for target.
InventarisMBG_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG_autogen.dir/build.make CMakeFiles/InventarisMBG_autogen.dir/build
.PHONY : InventarisMBG_autogen/fast

#=============================================================================
# Target rules for targets named test_algo_autogen_timestamp_deps

# Build rule for target.
test_algo_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_algo_autogen_timestamp_deps
.PHONY : test_algo_autogen_timestamp_deps

# fast build rule for target.
test_algo_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_algo_autogen_timestamp_deps.dir/build.make CMakeFiles/test_algo_autogen_timestamp_deps.dir/build
.PHONY : test_algo_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named test_algo_autogen

# Build rule for target.
test_algo_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_algo_autogen
.PHONY : test_algo_autogen

# fast build rule for target.
test_algo_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_algo_autogen.dir/build.make CMakeFiles/test_algo_autogen.dir/build
.PHONY : test_algo_autogen/fast

InventarisMBG_autogen/mocs_compilation.o: InventarisMBG_autogen/mocs_compilation.cpp.o
.PHONY : InventarisMBG_autogen/mocs_compilation.o

# target to build an object file
InventarisMBG_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG.dir/build.make CMakeFiles/InventarisMBG.dir/InventarisMBG_autogen/mocs_compilation.cpp.o
.PHONY : InventarisMBG_autogen/mocs_compilation.cpp.o

InventarisMBG_autogen/mocs_compilation.i: InventarisMBG_autogen/mocs_compilation.cpp.i
.PHONY : InventarisMBG_autogen/mocs_compilation.i

# target to preprocess a source file
InventarisMBG_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG.dir/build.make CMakeFiles/InventarisMBG.dir/InventarisMBG_autogen/mocs_compilation.cpp.i
.PHONY : InventarisMBG_autogen/mocs_compilation.cpp.i

InventarisMBG_autogen/mocs_compilation.s: InventarisMBG_autogen/mocs_compilation.cpp.s
.PHONY : InventarisMBG_autogen/mocs_compilation.s

# target to generate assembly for a file
InventarisMBG_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG.dir/build.make CMakeFiles/InventarisMBG.dir/InventarisMBG_autogen/mocs_compilation.cpp.s
.PHONY : InventarisMBG_autogen/mocs_compilation.cpp.s

src/core/Algorithms.o: src/core/Algorithms.cpp.o
.PHONY : src/core/Algorithms.o

# target to build an object file
src/core/Algorithms.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG.dir/build.make CMakeFiles/InventarisMBG.dir/src/core/Algorithms.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_algo.dir/build.make CMakeFiles/test_algo.dir/src/core/Algorithms.cpp.o
.PHONY : src/core/Algorithms.cpp.o

src/core/Algorithms.i: src/core/Algorithms.cpp.i
.PHONY : src/core/Algorithms.i

# target to preprocess a source file
src/core/Algorithms.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG.dir/build.make CMakeFiles/InventarisMBG.dir/src/core/Algorithms.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_algo.dir/build.make CMakeFiles/test_algo.dir/src/core/Algorithms.cpp.i
.PHONY : src/core/Algorithms.cpp.i

src/core/Algorithms.s: src/core/Algorithms.cpp.s
.PHONY : src/core/Algorithms.s

# target to generate assembly for a file
src/core/Algorithms.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG.dir/build.make CMakeFiles/InventarisMBG.dir/src/core/Algorithms.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_algo.dir/build.make CMakeFiles/test_algo.dir/src/core/Algorithms.cpp.s
.PHONY : src/core/Algorithms.cpp.s

src/core/InventoryManager.o: src/core/InventoryManager.cpp.o
.PHONY : src/core/InventoryManager.o

# target to build an object file
src/core/InventoryManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG.dir/build.make CMakeFiles/InventarisMBG.dir/src/core/InventoryManager.cpp.o
.PHONY : src/core/InventoryManager.cpp.o

src/core/InventoryManager.i: src/core/InventoryManager.cpp.i
.PHONY : src/core/InventoryManager.i

# target to preprocess a source file
src/core/InventoryManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG.dir/build.make CMakeFiles/InventarisMBG.dir/src/core/InventoryManager.cpp.i
.PHONY : src/core/InventoryManager.cpp.i

src/core/InventoryManager.s: src/core/InventoryManager.cpp.s
.PHONY : src/core/InventoryManager.s

# target to generate assembly for a file
src/core/InventoryManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG.dir/build.make CMakeFiles/InventarisMBG.dir/src/core/InventoryManager.cpp.s
.PHONY : src/core/InventoryManager.cpp.s

src/gui/LoginDialog.o: src/gui/LoginDialog.cpp.o
.PHONY : src/gui/LoginDialog.o

# target to build an object file
src/gui/LoginDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG.dir/build.make CMakeFiles/InventarisMBG.dir/src/gui/LoginDialog.cpp.o
.PHONY : src/gui/LoginDialog.cpp.o

src/gui/LoginDialog.i: src/gui/LoginDialog.cpp.i
.PHONY : src/gui/LoginDialog.i

# target to preprocess a source file
src/gui/LoginDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG.dir/build.make CMakeFiles/InventarisMBG.dir/src/gui/LoginDialog.cpp.i
.PHONY : src/gui/LoginDialog.cpp.i

src/gui/LoginDialog.s: src/gui/LoginDialog.cpp.s
.PHONY : src/gui/LoginDialog.s

# target to generate assembly for a file
src/gui/LoginDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG.dir/build.make CMakeFiles/InventarisMBG.dir/src/gui/LoginDialog.cpp.s
.PHONY : src/gui/LoginDialog.cpp.s

src/gui/MainWindow.o: src/gui/MainWindow.cpp.o
.PHONY : src/gui/MainWindow.o

# target to build an object file
src/gui/MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG.dir/build.make CMakeFiles/InventarisMBG.dir/src/gui/MainWindow.cpp.o
.PHONY : src/gui/MainWindow.cpp.o

src/gui/MainWindow.i: src/gui/MainWindow.cpp.i
.PHONY : src/gui/MainWindow.i

# target to preprocess a source file
src/gui/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG.dir/build.make CMakeFiles/InventarisMBG.dir/src/gui/MainWindow.cpp.i
.PHONY : src/gui/MainWindow.cpp.i

src/gui/MainWindow.s: src/gui/MainWindow.cpp.s
.PHONY : src/gui/MainWindow.s

# target to generate assembly for a file
src/gui/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG.dir/build.make CMakeFiles/InventarisMBG.dir/src/gui/MainWindow.cpp.s
.PHONY : src/gui/MainWindow.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG.dir/build.make CMakeFiles/InventarisMBG.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG.dir/build.make CMakeFiles/InventarisMBG.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/InventarisMBG.dir/build.make CMakeFiles/InventarisMBG.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

test_algo_autogen/mocs_compilation.o: test_algo_autogen/mocs_compilation.cpp.o
.PHONY : test_algo_autogen/mocs_compilation.o

# target to build an object file
test_algo_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_algo.dir/build.make CMakeFiles/test_algo.dir/test_algo_autogen/mocs_compilation.cpp.o
.PHONY : test_algo_autogen/mocs_compilation.cpp.o

test_algo_autogen/mocs_compilation.i: test_algo_autogen/mocs_compilation.cpp.i
.PHONY : test_algo_autogen/mocs_compilation.i

# target to preprocess a source file
test_algo_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_algo.dir/build.make CMakeFiles/test_algo.dir/test_algo_autogen/mocs_compilation.cpp.i
.PHONY : test_algo_autogen/mocs_compilation.cpp.i

test_algo_autogen/mocs_compilation.s: test_algo_autogen/mocs_compilation.cpp.s
.PHONY : test_algo_autogen/mocs_compilation.s

# target to generate assembly for a file
test_algo_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_algo.dir/build.make CMakeFiles/test_algo.dir/test_algo_autogen/mocs_compilation.cpp.s
.PHONY : test_algo_autogen/mocs_compilation.cpp.s

tests/test_algorithms.o: tests/test_algorithms.cpp.o
.PHONY : tests/test_algorithms.o

# target to build an object file
tests/test_algorithms.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_algo.dir/build.make CMakeFiles/test_algo.dir/tests/test_algorithms.cpp.o
.PHONY : tests/test_algorithms.cpp.o

tests/test_algorithms.i: tests/test_algorithms.cpp.i
.PHONY : tests/test_algorithms.i

# target to preprocess a source file
tests/test_algorithms.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_algo.dir/build.make CMakeFiles/test_algo.dir/tests/test_algorithms.cpp.i
.PHONY : tests/test_algorithms.cpp.i

tests/test_algorithms.s: tests/test_algorithms.cpp.s
.PHONY : tests/test_algorithms.s

# target to generate assembly for a file
tests/test_algorithms.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_algo.dir/build.make CMakeFiles/test_algo.dir/tests/test_algorithms.cpp.s
.PHONY : tests/test_algorithms.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... InventarisMBG_autogen"
	@echo "... InventarisMBG_autogen_timestamp_deps"
	@echo "... test_algo_autogen"
	@echo "... test_algo_autogen_timestamp_deps"
	@echo "... InventarisMBG"
	@echo "... test_algo"
	@echo "... InventarisMBG_autogen/mocs_compilation.o"
	@echo "... InventarisMBG_autogen/mocs_compilation.i"
	@echo "... InventarisMBG_autogen/mocs_compilation.s"
	@echo "... src/core/Algorithms.o"
	@echo "... src/core/Algorithms.i"
	@echo "... src/core/Algorithms.s"
	@echo "... src/core/InventoryManager.o"
	@echo "... src/core/InventoryManager.i"
	@echo "... src/core/InventoryManager.s"
	@echo "... src/gui/LoginDialog.o"
	@echo "... src/gui/LoginDialog.i"
	@echo "... src/gui/LoginDialog.s"
	@echo "... src/gui/MainWindow.o"
	@echo "... src/gui/MainWindow.i"
	@echo "... src/gui/MainWindow.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... test_algo_autogen/mocs_compilation.o"
	@echo "... test_algo_autogen/mocs_compilation.i"
	@echo "... test_algo_autogen/mocs_compilation.s"
	@echo "... tests/test_algorithms.o"
	@echo "... tests/test_algorithms.i"
	@echo "... tests/test_algorithms.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

