set(__QT_DEPLOY_TARGET_InventarisMBG_FILE /Users/patrick/Documents/System-manageFood/InventarisMBG)
set(__QT_DEPLOY_TARGET_InventarisMBG_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_test_algo_FILE /Users/patrick/Documents/System-manageFood/test_algo)
set(__QT_DEPLOY_TARGET_test_algo_TYPE EXECUTABLE)
